package com.nandi.gsgdsecond.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.nandi.gsgdsecond.bean.DisasterInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DISASTER_INFO".
*/
public class DisasterInfoDao extends AbstractDao<DisasterInfo, Long> {

    public static final String TABLENAME = "DISASTER_INFO";

    /**
     * Properties of entity DisasterInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property Find = new Property(2, boolean.class, "find", false, "FIND");
        public final static Property PhotoPath = new Property(3, String.class, "photoPath", false, "PHOTO_PATH");
        public final static Property Number = new Property(4, String.class, "number", false, "NUMBER");
    }


    public DisasterInfoDao(DaoConfig config) {
        super(config);
    }
    
    public DisasterInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DISASTER_INFO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"NAME\" TEXT," + // 1: name
                "\"FIND\" INTEGER NOT NULL ," + // 2: find
                "\"PHOTO_PATH\" TEXT," + // 3: photoPath
                "\"NUMBER\" TEXT);"); // 4: number
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DISASTER_INFO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, DisasterInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
        stmt.bindLong(3, entity.getFind() ? 1L: 0L);
 
        String photoPath = entity.getPhotoPath();
        if (photoPath != null) {
            stmt.bindString(4, photoPath);
        }
 
        String number = entity.getNumber();
        if (number != null) {
            stmt.bindString(5, number);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, DisasterInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
        stmt.bindLong(3, entity.getFind() ? 1L: 0L);
 
        String photoPath = entity.getPhotoPath();
        if (photoPath != null) {
            stmt.bindString(4, photoPath);
        }
 
        String number = entity.getNumber();
        if (number != null) {
            stmt.bindString(5, number);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public DisasterInfo readEntity(Cursor cursor, int offset) {
        DisasterInfo entity = new DisasterInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.getShort(offset + 2) != 0, // find
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // photoPath
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4) // number
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, DisasterInfo entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setFind(cursor.getShort(offset + 2) != 0);
        entity.setPhotoPath(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setNumber(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(DisasterInfo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(DisasterInfo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(DisasterInfo entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
